version: '3.7'
services:
  backend:
    container_name: backend
    build: ./backend
    image: backend:prod
    env_file: .env
    ports:
      - '3000:3000'
    links:
      - database
    networks:
      - internal-network
      - internet
    depends_on:
      - database
    restart: on-failure
  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend:prod
    ports:
      - '8081:80'
    depends_on:
      - backend
    restart: on-failure
  database:
    container_name: database
    image: 'postgres:12'
    env_file: .env
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - internal-network
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: on-failure
networks:
  internal-network:
    driver: bridge
    internal: true
  internet:
    driver: bridge
volumes:
  pg-data: {}